[meta]
name = "seefsBot"
run-mode = "debug"
server_address = ":8090"

[log]
log-path = "./log"
# 保存的最大天数
max-age = 30
# 日志文件小大（M）
max-size = 100
# 最多存在多少个切片文件
max-back-up = 60

[mysql]
host = "127.0.0.1"
port = 3306
user = "root"
password = "xuexiaojian"
db = "pixiv-bot"
charset = "utf8"
max-idle = 50
max-active = 100
max-lifetime = 30 # second

[serverchan]
sckey = "SCU50582T7e04cfb67db3abc2e8e28ee66f9aa82b5ccd0749a8cbd"

[bot]
token = "1416461032:AAENbSxxTeoaaOKuk5y-dRybn9B5EPyRHEU"
endpoint = "https://api.telegram.org"