[server]
addr = ":8080"
bot_token = "1580986280:AAEVgRmPNNkDAaOSMOg4h5MF2kUBlA3HFYw"

[mysql]
dsn = "root:123456@tcp(127.0.0.1:3306)/seefsbot?charset=utf8mb4&parseTime=True&loc=Local"

[redis]
addr = "127.0.0.1:6379"
db = 0
pass = ""

[log]
log_path = "./logs/"
log_name = "seefsBot"